#!/bin/sh

set -e

echo "\nBuilding site.js site…\n"

# Start fresh.
rm -rf tmp
rm -rf dist
mkdir tmp
mkdir dist

# CSS (temporary; to be collated into index later).
echo " > Minify CSS"
minify css/index.css >> tmp/styles.css

# JS (temporary; to be collated into index later).
echo " > Minify JS"
minify js/index.js >> tmp/scripts.js

# Inline the CSS and JS into the HTML.
echo " > Inline minified CSS & JS into HTML"
_build/inline-css-and-js.js

# Minify HTML.
echo " > Minify HTML"
minify tmp/index.html > tmp/index-minified.html

# Inline SVGs into the CSS.
echo " > Inline SVG into minified HTML"
cd _build
./inline-svg.js
cd ..

# Remove the tmp directory.
rm -rf tmp

# Copy image assets to dist.
echo " > Copy images"
mkdir dist/images
mkdir dist/images/emoji
cp images/site-js-logo.svg dist/images/site-js-logo.svg
cp images/emoji/0040_1f496.svg dist/images/emoji/0040_1f496.svg

# Copy binary releases.
echo " > Copy Site.js binary releases"
cp -R releases dist/

# Copy Nexe Node builds.
echo " > Copy Nexe Node builds"
cp -R nexe dist/

# Copy the dynamic routes.
echo " > Copy dynamic routes"
cp -R .dynamic dist/

# Copy install script.
echo " > Copy installation scripts"
cp installation-scripts/install dist/install
cp installation-scripts/install.txt dist/install.txt

echo "\nDone.\n"
