#!/bin/sh

set -e

echo "\nBuilding site.js site…\n"

# Start fresh.
rm -rf tmp
rm -rf dist
mkdir tmp
mkdir dist

# CSS (temporary; to be collated into index later).
echo " > Minify CSS"
minify css/highlight.js/github.css >> tmp/styles.css
minify css/index.css >> tmp/styles.css

# JS (temporary; to be collated into index later).
echo " > Minify JS"
minify js/index.js >> tmp/scripts.js

# Highlight code.
echo " > Highlight code"
_build/highlight-code.js

# Inline the CSS and JS into the HTML.
echo " > Inline minified CSS & JS into HTML"
_build/inline-css-and-js.js

# Minify HTML.
echo " > Minify HTML"
minify tmp/index.html > tmp/index-minified.html

# Inline SVGs into the CSS.
echo " > Inline SVG into minified HTML"
cd _build
./inline-svg.js
cd ..

# Remove the tmp directory.
rm -rf tmp

# Copy images.
echo " > Copy images"
mkdir dist/images
cp -R images/other dist/images

# Copy binaries.
echo " > Copy Site.js binary releases"
cp -R binaries dist/

# Copy Nexe Node builds.
echo " > Copy Nexe Node builds"
cp -R nexe dist/

# Copy the dynamic routes.
echo " > Copy dynamic routes"
cp -R .dynamic dist/

# Copy install script.
echo " > Copy installation scripts"
cp installation-scripts/install dist/install
cp installation-scripts/install.txt dist/install.txt

echo "\nDone.\n"
