#!/bin/sh

set -e

echo "Installing site.js site for development…"

# Install build dependencies.
echo " > Build dependencies"
npm install --global minify
npm install --global imagemin-cli
npm install --global svg-sprite

# Install Node dependencies.
echo " > Node dependencies."
npm install

echo " Done."
